### PR TITLE
refactor: :recycle: centralize the use of environment variables

### PR DESCRIPTION
**Pull request by emilioriosvz**
the dotenv library was imported from several files and where used without types. This change centralizes the import in a single file, adds types and default values

### CODE REVIEW

**Review by mnlc — APPROVED** [review]
LGTM

**Comment by emilioriosvz** [comment]
Any news about this?

**Comment by Viktor110** [comment]
> the dotenv library was imported from several files and where used without types. This change centralizes the import in a single file, adds types and default values

**Comment by emilioriosvz** [comment]
any news?

**Pull request closed without merging**
