### PR TITLE
Publication owner bypasses FollowValidationModuleBase's follow validation

### PR DESCRIPTION
**Pull request by donosonaumczuk**

### CODE REVIEW

**Comment by Zer0dot** [comment]
This is great! However, I think I would add some tests and then restructure the change to first short-circuit if the user is a follower before checking if they are the owner.

**Comment by donosonaumczuk** [comment]
> This is great! However, I think I would add some tests and then restructure the change to first short-circuit if the user is a follower before checking if they are the owner.

I already added tests, I think they are covering all the cases but let me know if you find something is missing.

And yeah, I think you are right, even when threads are really common, I think is more likely that comments comes from another account. Same with mirrors. I will push that small tweak tomorrow

**Comment by donosonaumczuk** [comment]
Well, it wasn't just a small tweak as I was expecting. I needed to refactor the reverting `validateFollow` to a boolean function `isFollowing` to be able to do the short-circuit, but it should be ready @Zer0dot !

**Comment by Zer0dot** [comment]
Looks good to me!

**Review by Zer0dot — CHANGES_REQUESTED** [review]
I would just add a test ensuring the behavior is as expected with collect modules as well.

**Comment by donosonaumczuk** [comment]
> I would just add a test ensuring the behavior is as expected with collect modules as well.

You're right, I have missed those. I added a pair, let me know!

**Comment by Zer0dot** [comment]
Looks good to me!

**Pull request merged**
